# Generated by Django 5.0.6 on 2024-08-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="province",
            field=models.CharField(
                choices=[
                    ("AB", "Alberta"),
                    ("BC", "British Columbia"),
                    ("MB", "Manitoba"),
                    ("NB", "New Brunswick"),
                    ("NL", "Newfoundland and Labrador"),
                    ("NS", "Nova Scotia"),
                    ("ON", "Ontario"),
                    ("PE", "Prince Edward Island"),
                    ("QC", "Quebec"),
                    ("SK", "Saskatchewan"),
                    ("NT", "Northwest Territories"),
                    ("NU", "Nunavut"),
                    ("YT", "Yukon"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
    ]
