# Generated by Django 5.0.6 on 2024-08-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_tax_province"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tax",
            name="country",
            field=models.CharField(default="CA", max_length=100),
        ),
        migrations.AlterField(
            model_name="tax",
            name="province",
            field=models.CharField(default="ON", max_length=100),
        ),
    ]
