# Generated by Django 5.0.6 on 2024-08-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_tax_country_alter_tax_province"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="shipping_price",
            new_name="shipping_amount",
        ),
        migrations.RenameField(
            model_name="cartorder",
            old_name="shipping_price",
            new_name="shipping_amount",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="service_fee",
        ),
        migrations.RemoveField(
            model_name="cartorder",
            name="service_fee",
        ),
        migrations.AddField(
            model_name="cart",
            name="grand_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="cart",
            name="sub_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="grand_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
