# Generated by Django 5.0.6 on 2024-09-12 05:05

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_remove_cart_grand_total_remove_cart_total_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorder",
            name="grand_total",
        ),
        migrations.RemoveField(
            model_name="cartorder",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="cartorderitem",
            name="service_fee",
        ),
        migrations.RemoveField(
            model_name="cartorderitem",
            name="shipping_price",
        ),
        migrations.RemoveField(
            model_name="cartorderitem",
            name="total_price",
        ),
        migrations.AddField(
            model_name="cartorder",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="shipping_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="cartorderitem",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="initial_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="saved",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="shipping_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="sub_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="tax_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="initial_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="oid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefghijklmnopqrstuvwxyz0123456789",
                length=20,
                max_length=29,
                prefix="ORDERITEM",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="saved",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="sub_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="tax_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=12, null=True
            ),
        ),
    ]
