# Generated by Django 5.0.6 on 2024-09-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_remove_cartorder_grand_total_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartorder",
            old_name="zip",
            new_name="postal_code",
        ),
        migrations.RenameField(
            model_name="cartorder",
            old_name="state",
            new_name="province",
        ),
        migrations.AddField(
            model_name="cartorder",
            name="apartment",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
