# Generated by Django 5.0.6 on 2024-09-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_rename_zip_cartorder_postal_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="apartment",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
