# Generated by Django 5.0.6 on 2024-09-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_alter_cartorder_apartment"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartorderitem",
            name="coupon",
            field=models.ManyToManyField(blank=True, to="store.coupon"),
        ),
    ]
